### ISSUE TITLE
 README file typos, grammar and clarity recommendations

### ISSUE THREAD

**Issue by jkomg** [IBM/Akka-cluster-deploy-kubernetes#6]
There are numerous typos, grammatical errors, and sentence fragments in the README file which should be corrected.

In the Overview section, the description of the distinction between Akka Cluster and Kubernetes is a somewhat confusing. It leaves the impression that Akka Cluster runs your application instead of it being used by your application as a library. Also, the statements about seed nodes being masters implies Akka Cluster
isn't peer-to-peer. It is.

I offering the following as a replacement for the current README text:
.....................

In this Code Pattern, we will deploy a simple Akka application on Kubernetes to demonstrate how you can build an inherently scalable, distributed solution.

Akka is “a set of open-source libraries for designing scalable, resilient systems that span processor cores and networks”. Akka Cluster, in particular, enables the distribution of an application over a cluster, thereby lending elasticity to the application by automatically scaling out or in with the number of members in the cluster. Kubernetes is a container orchestration platform and has the ability to automatically scale the number of pods up or down in response to workload. Together, the two work in concert: your Akka cluster expands automatically as Kubernetes scales the number of pods running for a particular Kubernetes deployment.

One key enabler of this elasticity is the ability for new nodes to join the Akka cluster automatically. Akka clusters are a peer-to-peer framework, however some nodes must be designated “seed” nodes when the cluster is initialized. These serve as an initial point of contact for new nodes. When new nodes are brought online, they can join the cluster automatically by first sending a message to all seed nodes in the cluster, followed by a “join” command to the seed node that responds first. Without seed nodes you would have to manually or programmatically add nodes to the cluster.

This solution uses Docker to build a single container image. In Kubernetes, we use StatefulSet rather than Deployment to guarantee the orderly startup of seed nodes.

**Comment by szihai** [comment]
changed.
